kind: pipeline
type: kubernetes
name: ci

steps:
  - name: submodules
    image: alpine/git
    commands:
        - git submodule update --init --recursive
  - name: test
    image: cubetiq/openjdk:11u-ubuntu
    commands:
      - apt-get update && apt-get install git -y
      - sh gradlew bootJar