kind: pipeline
type: kubernetes
name: container-pipeline

steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: git.cubetiqs.com/cubetiq/spring-web-modules
      registry: git.cubetiqs.com
      tags: latest

#---
#kind: pipeline
#type: kubernetes
#name: ci
#
#steps:
#  - name: submodules
#    image: alpine/git
#    commands:
#      - git submodule update --init --recursive
#  - name: test
#    image: cubetiq/openjdk:11u-ubuntu
#    commands:
#      - apt-get update && apt-get install git -y
#      - sh gradlew bootJar