kind: pipeline
type: docker
name: ci
steps:
  - name: submodules
    image: d.ctdn.net/alpine/git
    commands:
        - git submodule update --init --recursive
  - name: test
    image: d.ctdn.net/cubetiq/openjdk:11u-ubuntu
    commands:
      - apt-get update && apt-get install git -y
      - sh gradlew bootJar