apiVersion: v1
kind: Secret
metadata:
  namespace: spring-web-dev
  name: registry-secret
stringData:
  .dockerconfigjson: |
    {"auths":{"YOUR_PRIVATE_REGISTRY_HERE":{"auth":"YOUR_SECRET_HERE"}}}
type: kubernetes.io/dockerconfigjson

---
apiVersion: v1
kind: Secret
metadata:
  namespace: spring-web-dev
  name: spring-web-dev-secret
stringData:
  REDIS_HOST: redis-service
  REDIS_PASSWORD: demo
  POSTGRES_USER: demo
  POSTGRES_DB: demo
  POSTGRES_PASSWORD: demo
  APP_DATA_DIR: /opt/cubetiq/data
  MODULE_USER_ENABLED: true
  DATASOURCE_ENABLED: true
  REDIS_ENABLED: true
type: Opaque