http:
  port: ${HTTP_PORT:8080}
server:
  port: ${SERVER_PORT:8443}
  ssl:
    key-store: ${SERVER_SSL_KEY_STORE:classpath:keystore/server.jks}
    key-store-password: ${SERVER_SSL_KEY_STORE_PASSWORD:cubetiq}
    key-password: ${SERVER_SSL_KEY_PASSWORD:cubetiq}
    enabled: ${SERVER_SSL_ENABLED:true}
  compression:
    enabled: ${SERVER_COMPRESSION_ENABLED:${server.ssl.enabled}}

spring:
  profiles:
    active: ${APP_PROFILE:demo}
  application:
    name: ${SERVICE_NAME:cubetiq-api-service}
  redis:
    enabled: ${REDIS_ENABLED:false}
    host: ${REDIS_HOST:localhost}
    password: ${REDIS_PASSWORD:null}
  datasource:
    enabled: ${DATASOURCE_ENABLED:true}
    driverClassName: ${DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
    url: ${DATASOURCE_URL:jdbc:h2:file:${H2_DB_PATH:${cubetiq.app.data-dir}/data/db};DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${DATASOURCE_USERNAME:sa}
    password: ${DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:update}

module:
  user:
    enabled: ${MODULE_USER_ENABLED:true}
  uploader:
    enabled: ${MODULE_UPLOADER_ENABLED:true}
    local:
      path: ${MODULE_UPLOADER_FILE_PATH:${cubetiq.app.data-dir}/uploads}

cubetiq:
  app:
    data-dir: ${APP_DATA_DIR:${user.home}/${spring.application.name}}
    name: ${APP_NAME:CUBETIQ Web API}
    description: ${APP_DESCRIPTION:CUBETIQ Spring Web API's Documentation}

logging:
  file:
    path: ${LOGGING_FILE_PATH:${cubetiq.app.data-dir}/logs/}
    name: ${logging.file.path}/app.log

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui
